"""Plain-language in-app guide. Descriptions avoid guessing firmware-specific values."""

TOPICS = (
    ('Başlangıç','Hızlı başlangıç',
     '1. Demo ile arayüzü öğrenin.\n2. Pervaneleri söküp Cube Orange ve Here3 bağlantısını yerde doğrulayın.\n3. Cube bağlantısı penceresinden doğru COM portunu seçin.\n4. Güvenlik sayfasındaki kırmızı/BEKLE maddelerini çözün.\n5. Parametreleri değiştirmeden önce yedek alın.\n6. Rotayı gözden geçirip karta yükleyin.\n7. Önce STABILIZE, sonra ALT_HOLD/LOITER, RTL ve en son AUTO davranışını kontrollü ortamda deneyin.'),
    ('Başlangıç','Demo ve canlı bağlantı farkı',
     'SENTETİK DEMO yazısı görünüyorsa ekrandaki uçuş verileri örnektir ve karta komut gönderilmez. Canlı Cube bağlantısı kurulduğunda telemetri karttan gelir. Harita görüntüsü uydudan canlı takip değildir; İHA konumu Here3/GPS telemetrisinden alınır ve haritanın üzerine çizilir.'),
    ('Bağlantı','Cube bağlantısı',
     'Uçuş ekranındaki “CUBE’A BAĞLAN • CANLI KONUM” düğmesine basın. Açılan pencerede Seri / USB, telemetri radyosunun COM portu, 57600 baud ve Araç ID 1 seçilip “BAĞLAN VE CANLI KONUMU GÖSTER” düğmesine basılır. USB ile kalibrasyon ve yerde kurulum yapılabilir. Bağlı araç ArduPilot olarak doğrulanmadan kritik komutlar gönderilmez.'),
    ('Bağlantı','USB telemetriyi otomatik bulma',
     'Cube bağlantısı penceresi açıkken “USB telemetri takılınca otomatik bağlan” seçeneği COM portlarını izler. 57600, 115200, 230400, 460800 ve 921600 hızları denenir. Yalnız ArduPilot yaşam sinyali alınan port ve araç kimliği doğrulanınca canlı bağlantı başlar. Bağlantı koparsa önce aynı portta güvenli yeniden bağlanma denenir; uzun kesintide COM portları yeniden taranır. Mission Planner aynı portu kullanıyorsa tarama başarılı olamaz.'),
    ('Düğmeler','ARM / DISARM',
     'ARM motor çıkışlarının etkinleşmesine izin verir. Uygulama güncel heartbeat, ArduPilot kimliği, batarya, sensör, GPS ve EKF durumunu denetler. DISARM motor çıkışlarını kapatma isteğidir. Kartın kendi pre-arm denetimi son kararı verir.'),
    ('Düğmeler','Denge modu / STABILIZE',
     'Bağlantı yokken düğme yalnız sentetik İHA animasyonunu etkiler. Canlı Cube Orange bağlantısı kurulunca aynı düğme gerçek karta STABILIZE modu gönderir. Düğme ancak güncel ArduPilot heartbeat ve araç desteği doğrulandığında etkinleşir; komuttan sonra kartın heartbeat mesajındaki mod geri okunur.'),
    ('Düğmeler','Duraklat ve Baştan başlat',
     'Yalnız sentetik demoyu durdurur veya sıfırlar. Gerçek Cube uçuşunu durdurmaz ve gerçek karta yeniden başlatma komutu göndermez.'),
    ('Düğmeler','Bağlantı kaybını dene',
     'Yalnız demo telemetri bağlantısının kesilmiş görünmesini sağlar. Gerçek telemetri radyosunu veya Cube bağlantısını kapatmaz.'),
    ('Düğmeler','İHA’yı merkezle',
     'Harita görünümünü İHA işaretinin son bilinen konumuna getirir. Uçağa yön veya rota komutu göndermez.'),
    ('Düğmeler','Nokta ekle / güncelle / sil',
     'Görev taslağındaki waypoint listesini düzenler. Uygulamadaki eski 10 nokta sınırı kaldırılmıştır ve uzun listeler kaydırma çubuğuyla gezilebilir. Noktalar karta yüklenene kadar yalnız bilgisayardadır. Karta aktarılabilecek toplam sayı Cube belleğine ve MAVLink kapasitesine bağlıdır. İrtifa HOME konumunun üzerindeki metre değeridir.'),
    ('Düğmeler','Gözden geçir ve karta yükle',
     'Taslak görevi son kez gösterir ve onaydan sonra Cube üzerindeki görev belleğine aktarır. Yükleme uçuşu başlatmaz. Geri okuma eşleşmeden başarılı sayılmaz.'),
    ('Düğmeler','Karttaki görevi başlat',
     'Cube üzerinde daha önce yüklenmiş görevi AUTO olarak başlatmayı ister. ARM, HOME, GPS, EKF ve güncel konum doğrulanmadan komut engellenir.'),
    ('Düğmeler','Görevi duraklat / devam et / adıma geç',
     'Duraklat ve Devam et ArduPilot MAV_CMD_DO_PAUSE_CONTINUE komutunu kullanır. Belirli görev adımına geç, MISSION_SET_CURRENT isteği gönderir ve MISSION_CURRENT geri bildirimiyle doğrular. Araç hareketi değişebileceği için yalnız canlı görev izlenirken kullanılmalıdır.'),
    ('Kumanda','Doğrudan kontrol',
     'Tek İHA’ya MAVLink MANUAL_CONTROL yön komutları gönderir. Kontrol yalnız güncel ARMED bağlantı, MAV_OPTIONS bit 0 ve GCS sistem kimliği 255 doğrulandığında açılır. Gaz ekseni gönderilmez. Düğme bırakıldığında eksenler serbest bırakılır; fiziksel RC kumanda hazır tutulmalıdır.'),
    ('Görev','Rally ve güvenli iniş noktaları',
     'Rally noktaları ana görevden ayrı MAVLink 2 listesi olarak yüklenir ve geri okunur. ArduPilot, RALLY_INCL_HOME ve RALLY_LIMIT_KM gibi ayarlara göre RTL sırasında uygun rally noktasını seçebilir. Rally noktası tek başına otomatik ve güvenli iniş garantisi vermez.'),
    ('Harita','Ölçüm araçları',
     'İki rota noktası arasındaki kuş uçuşu mesafeyi, bütün rota ayaklarını, toplam yatay mesafeyi, noktaların kapattığı alanı ve girilen yatay hıza göre yaklaşık süreyi hesaplar. Süre tahmini tırmanış, rüzgâr, dönüş ve bekleme sürelerini içermez.'),
    ('Düğmeler','Tümünü karttan oku',
     'Bağlı Cube’un parametre listesini ister. Liste eksikse eksik indeksler tekrar istenir. Görülen değerler firmware ve araç türüne aittir.'),
    ('Düğmeler','Yedek kaydet / Dosyayla karşılaştır',
     'Yedek kaydet karttan alınmış değerleri .param dosyasına yazar. Karşılaştırma yalnız farkları taslak yapar; kendiliğinden karta yazmaz.'),
    ('Düğmeler','Taslağa al / Seçiliyi karta yaz',
     'Taslağa al yeni değeri yalnız ekranda hazırlar. Karta yaz düğmesi DISARMED bağlantı, kullanıcı onayı, sayısal tür kontrolü ve karttan geri doğrulama ister.'),
    ('Parametre','Değişiklik geçmişi ve geri alma',
     'Karttan PARAM_VALUE ile doğrulanmış her yazma, önceki ve yeni değeriyle oturum geçmişine eklenir. Geri alma yalnız kartın güncel değeri geçmişte kaydedilen yeni değerle aynıysa hazırlanır; DISARMED ve ikinci kullanıcı onayından sonra yazılıp tekrar karttan doğrulanır. Bilinen batarya, fence, RC ve servo alanları yerel aralık denetiminden geçer; bilinmeyen firmware parametresine aralık uydurulmaz.'),
    ('Kurulum','Gerçek kalibrasyon merkezi',
     'Cube bağlantı penceresinde USB yer kurulumu seçilip kart DISARMED doğrulandığında jiroskop, düz seviye, altı yön ivmeölçer, pusula, RC kumanda, ESC ve hava hızı kalibrasyon komutları açılır. Kartın ACK ve yön talepleri ekranda gösterilir. ESC için pervanelerin söküldüğü ayrıca onaylanır. Komutun kabul edilmesi fiziksel kalibrasyonun doğruluğunu tek başına kanıtlamaz.'),
    ('Kurulum','Güvenli motor ve servo testi',
     'Motor ve servo testi yalnız USB yer kurulumu, güncel DISARMED Cube, onay kutusu ve “PERVANELER SÖKÜLDÜ” metniyle açılır. Motor komutu %30 ve 5 saniye; servo komutu 3 saniye ile sınırlıdır. Servo otomatik nötr değere döner. Acil durdurma motorlara %0 ve aktif servoya nötr gönderir. Gözlenen motor yönü ve servo işlevleri JSON raporuna kaydedilebilir.'),
    ('Test','ArduPilot SITL testi',
     'SITL Testi sayfası yalnız bu bilgisayardaki 127.0.0.1:5760 veya :5762 adresine bağlanır. SIM_SPEEDUP parametresi okunmadan hedef simülatör kabul edilmez. Gerçek ArduPilot SITL telemetrisi okunduktan sonra uygulamanın GPS, batarya, sensör, EKF, HOME ve sanal çit kaybı engelleri sınanır. ArduPilot SITL ayrıca kurulup başlatılmalıdır.'),
    ('Uçuş modu','STABILIZE',
     'Pilot gazı ve yönü yönetir; kart yatış ve yunuslamayı dengeler. Konum tutmaz. İlk kontrollü uçuşlarda temel davranışın doğrulandığı moddur.'),
    ('Uçuş modu','ALT_HOLD',
     'Gaz çubuğuyla tırmanma/alçalma istenir; kart barometreyle irtifayı tutmaya çalışır. Yatay konumu GPS ile sabitlemez.'),
    ('Uçuş modu','LOITER',
     'Konum ve irtifayı tutmaya çalışır. Sağlıklı konum çözümü gerekir. Uygulama güncel GPS, EKF ve konum olmadan isteği engeller.'),
    ('Uçuş modu','RTL',
     'Aracı kaydedilmiş HOME konumuna döndürme davranışıdır. GPS, EKF ve doğru HOME konumuna bağlıdır; sensör arızasında evrensel bir kurtarma yöntemi değildir.'),
    ('Uçuş modu','LAND',
     'Bulunduğu yerde kontrollü alçalma ve iniş davranışı ister. GPS olmadan kullanılabilse de aracın yönelimi, irtifa algısı ve fiziksel alan güvenli olmalıdır.'),
    ('Uçuş modu','AUTO',
     'Cube üzerinde yüklü görev adımlarını yürütür. Uygulama ARM, HOME, GPS, EKF ve konum koşulları sağlanmadan AUTO/görev başlatmayı engeller.'),
    ('Uçuş modu','GUIDED',
     'Yer istasyonundan veya yardımcı bilgisayardan gönderilen hedeflere yönelir. Geçerli konum ve kesintisiz komut/telemetri tasarımı gerekir.'),
    ('Güvenlik','BEKLE ve UYGUN ne demek?',
     'BEKLE ilgili ölçümün eksik, eski veya güvenlik sınırının dışında olduğunu gösterir. UYGUN yalnız uygulamanın o anki yazılım kontrolünün geçtiğini söyler; uçuş garantisi değildir.'),
    ('Güvenlik','Gerçek donanım kabul testi',
     'Güvenlik sayfasında önce USB yer testi, ardından Kablosuz telemetri / uçuş öncesi aşaması çalıştırılır. Test salt okunurdur; motora, servoya, ARM veya moda komut göndermez. Heartbeat, ArduPilot kimliği, DISARMED durumu, kart ve sensör sağlığı, Here3/GPS, canlı konum, EKF, batarya, HOME, ARMING_CHECK, BATT_MONITOR, telemetri failsafe, temel modlar ve SiK RADIO_STATUS kontrol edilir. Kritik alanlar en az beş saniye kesintisiz uygun kalmadan sonuç UYGUN olmaz. Rapor kaydedilebilir; yine de pervaneler sökülü masa testi ve kontrollü saha denemesi gerekir.'),
    ('Güvenlik','Önerilen deneme sırası',
     'Pervanesiz masa testi ve yön/motor doğrulamasından sonra kontrollü alanda STABILIZE, ALT_HOLD, LOITER, RTL ve AUTO sırasıyla denenir. Her aşamada pilotun güvenli manuel moda dönebilmesi gerekir.'),
    ('Harita','Dünya, uydu ve 3D haritalar',
     'Dünya Haritası OpenStreetMap, Uydu Görüntüsü Esri döşemelerini kullanır. Google Uydu görünümü kullanıcının Maps Static API anahtarıyla alınır; anahtar dosyaya yazılmaz ve Google kota/faturalandırması geçerlidir. 3D görünüm OSM bina/yol verilerinden çizilen bir sahnedir. Here3 konum üretmek için internet kullanmaz.'),
    ('Telemetri','Kablosuz telemetri bağlantı kalitesi',
     'Radyo RADIO_STATUS gönderirse yerel/uzak RSSI, gürültü, gönderim tamponu, alım hataları ve düzeltilen paketler gösterilir. MAVLink sıra numarası boşlukları yaklaşık paket kaybı olarak hesaplanır. Bu değerler RF menzil garantisi değildir; yerde menzil testi gerekir.'),
    ('Güvenlik','Yerde senaryo testi',
     'Gerçek bağlantı kesilmeden ve araç hareket ettirilmeden, seçilen kayıp veya arıza için ilgili failsafe parametresinin karttan okunup okunmadığını gösterir. Sayısal seçeneğin anlamı bağlı firmware sürümünden doğrulanır; test gerçek failsafe tetiklemez.'),
    ('Telemetri','Veri yok ve ESKİ',
     '“Veri yok” alan için karttan mesaj alınmadığını, “ESKİ” son verinin üç saniyeden eski olduğunu gösterir. Eski konum canlı konum olarak kullanılmaz.'),
    ('Telemetri','Canlı batarya göstergesi',
     'Cube’a bağlı güç modülü veya desteklenen batarya monitörü ölçüm üretirse ana Sistem Durumu panelinde kalan yüzde, voltaj, anlık akım ve tüketilen mAh gösterilir. SENTETİK etiketi demo verisini, CANLI CUBE etiketi güncel kart ölçümünü, SON VERİ etiketi telemetri kesilmeden önceki eski ölçümü belirtir. Değer yoksa çizgi görünür; uygulama tahmini değer üretmez. Ölçüm bir multimetre veya güç analizörüyle doğrulanmalı, düşük ve kritik batarya failsafe ayarları uçuş öncesinde kartta yapılandırılmalıdır.'),
    ('Kamera','USB ve ağ kamerası',
     'Kamera görüntüsü sayfasında USB Kamera 0/1 veya RTSP/HTTP yayını açılabilir. Fotoğraf PNG olarak, zaman/konum/görev adımı bilgisi ayrı JSON etiketiyle kaydedilir; video MP4 olarak kaydedilebilir. Canlı Cube bağlantısında kullanıcı onayıyla gimbal pitch/yaw hedefi ve MAVLink tek fotoğraf tetikleme komutu gönderilebilir. Kamera veya gimbalın komutu desteklemesi kendi donanımı ve ArduPilot yapılandırmasına bağlıdır.'),
    ('Güvenlik','Sesli ve renkli uyarılar',
     'Uyarılar sayfası gerçek Cube verisinden düşük/kritik batarya, GPS çözümü kaybı, telemetri yaşam sinyali kaybı, zayıf SiK sinyal-gürültü farkı, yüksek MAVLink paket kaybı, FENCE_STATUS ihlali ve kritik kart mesajlarını izler. Ses susturulsa da üstteki renkli durum ve geçmiş kaydı çalışır. Uygulama uyarısı kartın kendi batarya, GCS, GPS veya sanal çit failsafe ayarlarının yerine geçmez.'),
    ('Yardım','Pilot Arı',
     'Pilot Arı varsayılan olarak bilgisayarda yerel çalışan, salt okunur karar destek sohbetidir. Yerel mod son sekiz soru/yanıtı hatırlar; özetleme, adım adım anlatma ve örnek verme gibi devam isteklerini önceki konuya bağlar. Uzun bir mesajdaki telemetri, GPS ve batarya sorunlarını ayrı başlıklarla cevaplayabilir, belirsiz soruyu önceki mesajla birleştirerek açıklama ister ve daha geniş günlük sohbet kalıplarını tanır. “AI ayarları” ekranına kullanıcının kendi OpenAI API anahtarı girilip açık veri onayı verildiğinde GPT-5.4 mini veya daha ekonomik GPT-5.4 nano ile daha doğal ve ayrıntılı sohbet eder. Anahtar dosyaya kaydedilmez ve bulut istekleri store=false ile yapılır. Bulut AI’ye mesaj, son 12 kısa sohbet ile yalnız araç türü, canlı/demo kaynağı, telemetri güncelliği, ARM, mod, batarya, GPS fix/uydu sayısı ve uyarı başlıkları gönderilebilir; kesin GPS koordinatı, COM portu, tam olay günlüğü ve API anahtarı gönderilmez. Bulut bağlantısı başarısız olursa yerel bilgi sistemi yanıt verir. Canlı Cube bağlantısı varsa durumu yorumlar ama karta ARM, mod, görev, motor veya parametre komutu göndermez. Güncel hava Open-Meteo üzerinden ayrı olarak alınır. OpenAI API kullanıma göre ücretli olabilir; anahtar ve faturalandırma kullanıcı hesabına aittir. Pilot Arı uçuş izni ya da güvenlik garantisi vermez.'),
    ('Yardım','Pilot Arı donanım ve performans hesabı',
     'Pilot Arı sayfasındaki Donanım hesabı düğmesi yerel RAG bilgi kütüphanesini ve formül tabanlı hesap motorunu açar. Örnek giriş: “Toplam ağırlık 1450 g, 4 motor, motor başına itki 900 g, batarya 5200 mAh, ortalama akım 22 A, voltaj 14.8 V.” Çok rotorlu araçta toplam statik itki, itki/ağırlık oranı, motor başına askıda kalma yükü ve yaklaşık azami itki yüzdesi; uygun batarya verisiyle %80 kullanıl/güvenlik payı varsayımına dayalı yaklaşık süre ve Wh hesaplanır. Sabit kanatta kanat alanı dm² verilirse kanat yüklemesi gösterilir. Motor KV tek başına taşınabilecek gramı göstermez. Hesap eksik değeri uydurmaz; üreticinin aynı motor-pervane-gerilim test tablosu, terazi, wattmetre ve güvenli yer testiyle doğrulanmalıdır. `belgeler` klasörüne eklenen UTF-8 `.txt` dosyaları, gönderilen RAG örneğindeki 600 karakter/80 karakter örtüşmeli parçalama yöntemiyle yerel dizine eklenir.'),
    ('Yardım','Pilot Arı parça kontrolü',
     'Pilot Arı sayfasındaki Parça kontrolü düğmesi seçili araç türüne göre temel donanım listesini açar. Kullanıcı “Elimde Cube Orange, Here3, dört motor, ESC ve batarya var; başka ne gerekli?” gibi bir mesaj yazabilir. Pilot Arı konuşma boyunca belirtilen parçaları hatırlar; Döner kanat, Sabit kanat ve FPV için farklı temel sistem, konum/telemetri ve önerilen kurulum-güvenlik donanımı listeleri oluşturur. Ayrıca motor-pervane-batarya, ESC akımı, batarya C değeri, kablo/konektör, BEC, port/protokol, toplam ağırlık ve ağırlık merkezi uyumluluk kontrollerini sıralar. Parça adı tek başına uyumluluk veya uçuşa hazır sonucu üretmez; kesin model ve elektriksel değerler gerekir.'),
)

PARAMETERS = {
    'ARMING_CHECK': ('Güvenlik','ARM öncesinde yapılacak kart kontrollerinin bit maskesidir. 0 tüm kontrolleri kapatır ve uygulama bu yazmayı engeller. Genellikle tüm kontrollerin açık tutulması gerekir.'),
    'ARMING_SKIPCHK': ('Güvenlik','Belirli ARM kontrollerini atlamaya yarar. Sıfır dışındaki yazımlar bu uygulamada engellenir.'),
    'FS_GCS_ENABLE': ('Failsafe','Yer istasyonu/telemetri bağlantısı kaybında uygulanacak davranışı seçer. Sayısal seçenekler araç türüne ve firmware sürümüne göre değişebilir.'),
    'FS_THR_ENABLE': ('Failsafe','Kumanda sinyali kaybında uygulanacak davranışı seçer. Alıcı failsafe ayarı ve RC kalibrasyonuyla birlikte doğrulanmalıdır.'),
    'BATT_MONITOR': ('Batarya','Batarya ölçüm kaynağını ve monitör türünü seçer. Yanlış seçim voltaj/akım bilgisinin kaybolmasına yol açabilir.'),
    'BATT_CAPACITY': ('Batarya','Bataryanın nominal kapasitesidir ve mAh cinsindedir. Kalan kapasite hesabı ve tüketim uyarıları için kullanılır.'),
    'BATT_LOW_VOLT': ('Batarya','Düşük batarya voltaj eşiğidir. Hücre sayısı, batarya kimyası ve yük altındaki voltaj düşümü dikkate alınmalıdır.'),
    'BATT_CRT_VOLT': ('Batarya','Kritik batarya voltaj eşiğidir. Düşük eşikten daha ciddi failsafe davranışını tetikleyebilir.'),
    'BATT_FS_LOW_ACT': ('Batarya','Düşük batarya failsafe oluştuğunda yapılacak eylemdir. Seçenek numaraları firmware/araç türüne göre kart dokümanından doğrulanmalıdır.'),
    'BATT_FS_CRT_ACT': ('Batarya','Kritik batarya failsafe eylemidir. Uçuş alanı ve araç tipi düşünülmeden değiştirilmemelidir.'),
    'RTL_ALT': ('RTL','Copter RTL sırasında hedeflenen dönüş irtifasıyla ilişkilidir. Birimi ve özel 0 davranışı kartın firmware açıklamasından doğrulanmalıdır.'),
    'RTL_SPEED': ('RTL','RTL yatay hızını sınırlar. Sıfır gibi özel değerlerin anlamı firmware sürümüne bağlı olabilir.'),
    'RTL_LOIT_TIME': ('RTL','HOME üzerinde inişten önce beklenecek süredir; genellikle milisaniye cinsindedir.'),
    'FENCE_ENABLE': ('Sanal çit','Kartın sanal çit denetimini etkinleştirir. Çit türü ve eylemi ayrıca yapılandırılmalıdır.'),
    'FENCE_TYPE': ('Sanal çit','Yükseklik, dairesel sınır ve çokgen gibi hangi çit türlerinin kullanılacağını belirleyen bit maskesidir.'),
    'FENCE_ALT_MAX': ('Sanal çit','HOME üstündeki azami irtifa sınırıdır. Birim kart parametre açıklamasından doğrulanmalıdır.'),
    'FENCE_RADIUS': ('Sanal çit','HOME çevresindeki yatay sınır yarıçapıdır.'),
    'FLTMODE_CH': ('Uçuş modu','Kumandada uçuş modu seçimi için kullanılan RC kanalını belirler.'),
    'SERIAL1_PROTOCOL': ('Bağlantı','İlgili seri portun MAVLink, GPS veya başka hangi protokolü taşıdığını belirler. Aktif telemetri portunda yanlış değer bağlantıyı kesebilir.'),
    'SERIAL1_BAUD': ('Bağlantı','İlgili seri portun haberleşme hızıdır. Telemetri radyosunun hızıyla eşleşmelidir.'),
    'GPS1_TYPE': ('GPS','Birinci GPS kaynağının türünü/protokolünü seçer. Here3 DroneCAN kurulumu CAN ve GPS ayarlarıyla birlikte yapılır.'),
    'CAN_P1_DRIVER': ('DroneCAN','Birinci CAN portunun hangi CAN sürücüsünü kullanacağını seçer. Here3 gibi DroneCAN cihazlarının görülebilmesi için ilgili CAN hattı doğru kurulmalıdır.'),
    'MAV_OPTIONS': ('Kumanda','MAVLink üzerinden RC/MANUAL_CONTROL girişinin kabulüyle ilgili seçenek bitlerini içerir. Doğrudan kontrol için bit 0 açık olmalıdır.'),
    'MAV_GCS_SYSID': ('Kumanda','MAVLink pilot girdisini göndermesine izin verilen GCS sistem kimliğidir. Fentek bağlantısı kaynak sistem kimliği 255 kullanır.'),
    'RALLY_INCL_HOME': ('Rally','HOME konumunun rally seçimine dahil edilmesiyle ilgilidir. Davranış araç türü ve firmware sürümünden doğrulanmalıdır.'),
    'RALLY_LIMIT_KM': ('Rally','Bir rally noktasının RTL seçimi için kabul edilebileceği azami uzaklıkla ilgilidir.'),
}

PREFIXES = (
    ('FLTMODE','Uçuş modu','Kumanda anahtarının ilgili konumunda seçilecek uçuş modudur.'),
    ('FS_','Failsafe','Bağlantı, kumanda veya başka bir arıza durumundaki koruma davranışıyla ilgilidir.'),
    ('BATT','Batarya','Batarya ölçümü, kapasitesi, eşikleri veya batarya failsafe davranışıyla ilgilidir.'),
    ('RTL','RTL','Eve dönüş irtifası, hızı, bekleme süresi veya son davranışıyla ilgilidir.'),
    ('FENCE_','Sanal çit','Sanal çit türü, sınırı, marjı veya ihlal eylemiyle ilgilidir.'),
    ('ARMING_','Güvenlik','ARM koşulları ve uçuş öncesi güvenlik kontrolleriyle ilgilidir.'),
    ('GPS','GPS','GPS alıcısı, otomatik seçim, protokol veya konum kaynağı ayarıyla ilgilidir.'),
    ('CAN_','DroneCAN','CAN portu, sürücüsü veya DroneCAN düğüm ayarıyla ilgilidir.'),
    ('SERIAL','Bağlantı','Seri portun protokolü veya veri hızıyla ilgilidir.'),
    ('SERVO','Çıkışlar','Servo/motor çıkış işlevi, sınırı veya yönüyle ilgilidir.'),
    ('RC','Kumanda','Kumanda kanal kalibrasyonu, seçenekleri veya kanal işleviyle ilgilidir.'),
    ('ARSPD','Hava hızı','Sabit kanat hava hızı sensörü ve kalibrasyonuyla ilgilidir.'),
)

def parameter_help(name):
    name=str(name).strip().upper()
    if name in PARAMETERS:
        category,description=PARAMETERS[name]
        return category,description
    for prefix,category,description in PREFIXES:
        if name.startswith(prefix):
            return category,description+' Bu tam parametrenin birimi, sınırı ve seçenekleri bağlı kartın firmware sürümüne göre doğrulanmalıdır.'
    return 'Firmware özel','Bu parametre için uygulamada doğrulanmış açıklama yok. Anlamı, birimi ve değer aralığı bağlı aracın ArduPilot sürümündeki parametre açıklamasından doğrulanmadan değiştirilmemelidir.'
